#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# IMPORTANT: This project's gradle/wrapper/gradle-wrapper.jar is NOT included in this
# generated source tree (binary jars cannot be produced by this build assistant). CI
# (.github/workflows/build.yml) works around this by installing Gradle directly via
# gradle/actions/setup-gradle and invoking `gradle` instead of `./gradlew`.
#
# To use this script locally, first generate the wrapper jar with a local Gradle install:
#   gradle wrapper --gradle-version 8.7
# which will populate gradle/wrapper/gradle-wrapper.jar, after which this script works
# normally.
#

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)

APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: gradle/wrapper/gradle-wrapper.jar is missing." >&2
    echo "Run 'gradle wrapper --gradle-version 8.7' with a local Gradle install to generate it," >&2
    echo "or use the 'gradle' command directly (this is what CI does)." >&2
    exit 1
fi

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
